### PR TITLE
fix go.mod

### LINKED ISSUE #60: go.mod is missing v3 label
From https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg"). This includes the paths used in go get commands (e.g., go get github.com/my/mod/v2@v2.0.1. Note there is both a /v2 and a @v2.0.1 in that example. One way to think about it is that the module name now includes the /v2, so include /v2 whenever you are using the module name).

go.mod thusly should be `module github.com/zencoder/go-dash/v3` (note the added `/v3`)

Otherwise, other projects attempting to import this module will encounter the following error:

> go: github.com/zencoder/go-dash/v3@v3.0.0: go.mod has non-.../v3 module path "github.com/zencoder/go-dash" (and .../v3/go.mod does not exist) at revision v3.0.0

### PR DESCRIPTION
**Pull request by jslching**
Fixes #60

### CODE REVIEW

**Comment by stuarthicks** [comment]
Please see the discussion on https://github.com/zencoder/go-dash/pull/58. Changing the module line by itself breaks the build. I'll be happy to accept this PR if it includes the other necessary changes to imports. Thank you.

**Comment by jslching** [comment]
@stuarthicks Please see the additional changes, thank you.

**Comment by jslching** [comment]
@stuarthicks any possibility of an update on this? Thank you

**Comment by stuarthicks** [comment]
@jslching Hi, I'm really sorry for never getting back onto this, it somewhat fell off my radar. The changes you pushed look good and I'm happy to merge. Thanks!

**Pull request merged**
